blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:pk>/', views.post_detail, name='post_detail'),
    path('category/<slug:category_slug>/', views.category_posts,
         name='category_posts'),
]

blogicum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('pages/', include('pages.urls', namespace='pages')),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('rules/', views.rules, name='rules'),
]

blog/views.py
from django.shortcuts import render

posts = [
    {'id': 0, 'location': 'Остров отчаянья', 'date': '30 сентября 1659 года',
        'category': 'travel',
        'text': 'Наш корабль, застигнутый в открытом море\n'
                '                страшным штормом, потерпел крушение.\n'
                '                Весь экипаж, кроме меня, утонул; я же,\n'
                '                несчастный Робинзон Крузо, был выброшен\n'
                '                полумёртвым на берег этого проклятого '
                'острова,\n'
                '                который назвал островом Отчаяния.', },
    {'id': 1, 'location': 'Остров отчаянья', 'date': '1 октября 1659 года',
        'category': 'not-my-day',
        'text': 'Проснувшись поутру, я увидел, что наш корабль сняло\n'
                '                с мели приливом и пригнало гораздо ближе '
                'к берегу.\n'
                '                Это подало мне надежду, что, когда ветер '
                'стихнет,\n'
                '                мне удастся добраться до корабля и запастись '
                'едой и\n'
                '                другими необходимыми вещами. Я немного '
                'приободрился,\n'
                '                хотя печаль о погибших товарищах не '
                'покидала меня.\n'
                '                Мне всё думалось, что, останься мы '
                'на корабле, мы\n'
                '                непременно спаслись бы. Теперь из его '
                'обломков мы могли бы\n'
                '                построить баркас, на котором и выбрались '
                'бы из этого\n'
                '                гиблого места.', },
    {'id': 2, 'location': 'Остров отчаянья', 'date': '25 октября 1659 года',
        'category': 'not-my-day',
        'text': 'Всю ночь и весь день шёл дождь и дул сильный\n'
                '                порывистый ветер. 25 октября.  Корабль '
                'за ночь '
                'разбило\n'
                '                в щепки; на том месте, где он стоял, торчат '
                'какие-то\n'
                '                жалкие обломки,  да и те видны только '
                'во время '
                'отлива.\n'
                '                Весь этот день я хлопотал  около вещей: '
                'укрывал и\n'
                '                укутывал их, чтобы не испортились от '
                'дождя.', },
]


def index(request):
    return render(request, 'blog/index.html', {'posts': posts})


def post_detail(request, pk):
    post = next((post for post in posts if post['id'] == pk), None)
    return render(request, 'blog/detail.html', {'post': post})


def category_posts(request, category_slug):
    return render(request, 'blog/category.html',
                  {'category_slug': category_slug})

pages/views.py
from django.shortcuts import render


def about(request):
    return render(request, 'pages/about.html')


def rules(request):
    return render(request, 'pages/rules.html')

templates/base.html
{% load  static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image/x-icon">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}Блогикум{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-light" style="background-color: lightskyblue">
            <div class="container">
                <a class="navbar-brand" href="{% url 'blog:index' %}">
                    <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
                    Блогикум
                </a>
                <ul class="nav nav-pills">
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'index' %}active{% endif %}" href="{% url 'blog:index' %}">Лента записей</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'about' %}active{% endif %}" href="{% url 'pages:about' %}">О проекте</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'rules' %}active{% endif %}" href="{% url 'pages:rules' %}">Наши правила</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="container py-5">
        {% block content %}{% endblock %}
    </main>
    <footer class="border-top text-center py-3">
        <p>© Блогикум</p>
    </footer>
</body>
</html>

templates/blog/category.html
{% extends "base.html" %}

{% block title %}Категория: {{ category_slug }}{% endblock %}

{% block content %}
<h1>Публикации в категории - {{ category_slug }}</h1>
{% endblock %}

templates/blog/detail.html
{% extends "base.html" %}

{% block title %}{{ post.location }}. {{ post.date }}{% endblock %}

{% block content %}
<h1>{{ post.location }}</h1>
<p>{{ post.date }}</p>
<p>{{ post.text }}</p>
{% endblock %}

templates/blog/index.html
{% extends "base.html" %}

{% block title %}Лента записей{% endblock %}

{% block content %}
<h1>Лента записей</h1>
<ul class="list-group">
    {% for post in posts reversed %}
    <li class="list-group-item">
        <h2>
            <a href="{% url 'blog:post_detail' post.id %}">{{ post.text|truncatechars:50 }}</a>
        </h2>
        <p>{{ post.date }} — {{ post.location }}</p>
    </li>
    {% endfor %}
</ul>
{% endblock %}

templates/pages/about.html
{% extends "base.html" %}

{% block title %}О проекте{% endblock %}

{% block content %}
<h1>О проекте</h1>
<p>Блогикум — это дом для творческих людей...</p>
{% endblock %}

templates/pages/rules.html
{% extends "base.html" %}

{% block title %}Наши правила{% endblock %}

{% block content %}
<h1>Наши правила</h1>
<p>Правила использования сайта...</p>
{% endblock %}